= Keyboards

== Overview

Keyboards are generated on a per-language basis from source files in a repository on GitHub for that language, nominally under the `giellalt` organisation and prefixed with `keyboard-XXX` where XXX is the ISO 639-3 language code. For example, North Sami is `giellalt/keyboard-sme`.

These repositories essentially only contain the files necessary to support keyboard generation. This means that there is a `kbdgen` bundle in the root directory, prefixed with the language code (e.g. `sme.kbdgen`). the structure of this bundle and how to create keyboard layouts is documented separately in the kbdgen documentation.

These repositories are used as resources for continuous integration (CI) and continuous delivery (CD) tools. This means that when a change is made to the keyboard layout files and committed to the git repository, a build is immediately triggered on GitHub Actions to confirm that your changes were valid. A build will then be pushed to our Pahkat repositories onto the `nightly` channel so that they may be tested.

However, the above only applies to Windows and macOS keyboards. If you are developing an iOS or Android keyboard, you will still provide your layout files in one of these repositories, only the build process is different. Due to how mobile operating systems are architectured, we need to bundle all the keyboards we intend to use as part of an app. Our iOS app is in the `divvun/divvun-keyboard-ios` repository, and for Android it is `divvun/divvun-keyboard-android` repository.

At the time of writing, triggering these builds based on changes to the source material is manual due to a lack of support for job pipelining in GitHub Actions.

== Project Goals



== Tips for sysadmins

=== Windows

On Windows, when you install a keyboard with Divvun Manager (previously known as Divvun Installer), the keyboard will no longer be automatically enabled for the current user. Previous versions of this installer _only_ enabled the keyboard for the current user, and caused some confusion in multi-user environments.

For each language that is installed, a new "start menu" item is created with a localised variant of "Enable <language name> Keyboard". This enables the keyboard for the current user and adds the necessary language to the language list.

For specific changes made to the registry to enable this behaviour, please refer to the kbdgen documentation.

== Mobile keyboards

=== Overview


=== User dictionary functionality

Each keyboard includes user dictionary

=== DivvunSpell integration

Our Android and iOS keyboards integrate our speller library DivvunSpell, a derivative of hfst-ospell. This library includes tokenisation and capitalisation support. However, it also specifically only uses memory mapped data, so RAM usage is extremely minimal for our spellers (roughly 5MB on iOS and similar on Android).

We also on mobile use a speller bundle format optimised for usage on mobiles -- BHFST. Unlike .zhfst files, .bhfst files use a new format called .box to bundle the internal files. .box was created to correct several deficiencies in .zip, with a focus on ensuring aligned reads (this stops our spellers crashing on 32bit ARM processors) and simplifying the dependencies needed to load the files in the first place.

Another difference is what is inside the bundle. Instead of containing an index.xml and some .hfst files, there are bundles known as .thfst bundles, and a meta.json. By using JSON, we alleviate needing an XML dependency on all platforms we support, and simplify the parsing significantly. THFST bundles (named Tromsø-Helsinki Finite State Transducer) are simply a slightly more optimised variant of the optimized lookup HFST format. The header is stripped into a separate file, and all fields are 4-byte aligned so that reads never require a copy and that lookups do not cause unaligned read crashes.

DivvunSpell itself is then hooked into a Swift or Kotlin module using a C foreign function interface to the underlying DivvunSpell Rust library. This means that uses of these platforms need not deal with the intricacies of the Rust library and can use their preferred language directly. This interface also reveals the tokenizer interface, which is important for determining word endings.

These interfaces tend to be integrated into a banner plugin or equivalent functionality on the mobile platform. On iOS, our giellakbd-ios codebase has a plugin interface specifically crafted for simply adding new plugins. On Android, we maintain a fork of the Android Open Source Project keyboard -- there are less clean interfaces here, but the implementation can be found in the `no.divvun` namespace.

=== Pahkat integration

Speller files are not packaged with the keyboards installed from the Google Play Store or the Apple App Store. Instead, they are downloaded on-demand for the enabled keyboards. This also means that the speller files are updated in the background without any user interaction.

To enable this, we use our Pahkat package management library and servers. Each kbdgen keyboard definition has a directive to use a speller, using a Pahkat URL and the specific file within the package to use.
